"""
Django settings for nexuselectric project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, platform

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ed*p(3#j0zp1rhahu5#(e0ayq89iofoub4n_7rjz%)p#3o6@)a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'front_end.apps.FrontEndConfig',
    'back_end.apps.BackEndConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nexuselectric.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front_end/templates/html')],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nexuselectric.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# specific changes for WSL
if('microsoft' in platform.release()):
    DATABASES = {
        'default': {
            'NAME': 'energy',
            'ENGINE': 'django.db.backends.mysql',
            'USER': 'django',
            'PASSWORD': 'XR^Sq@!KhQw%8A6W',
            'HOST':'0.0.0.0',
            'PORT':'3306',
        }
    }
else:
    DATABASES = {
    'default': {
        'NAME': 'energy',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'django',
        'PASSWORD': 'XR^Sq@!KhQw%8A6W',
        'HOST':'127.0.0.1',
        'PORT':'3306',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'front_end/static')
#]

# REST-FRAMEWORK
REST_FRAMEWORK = {
	'DEFAULT_RENDERER_CLASSES': [
		#'rest_framework.renderers.BrowsableAPIRenderer', #this has to be removed for final exams
		'rest_framework.renderers.JSONRenderer',
		'rest_framework_csv.renderers.CSVRenderer',
	],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'back_end.authentication.NexusTokenAuthentication'
    ],
}